extensions:
  square_payments:
    application_id: "sandbox-sq0idb-PNinb0DahX2qpqq-cEEclg"
    location_id: "LYQA581ZDVC8V"
    access_token: "EAAAEPaLTZOz5428wvE2Wksz6nzLic8GLFPjEKNQvUFlsfTUXGIEmh4tBR4vgwiV"